// <auto-generated />
using System;
using ContadorHandy.AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContadorHandy.AccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230802001021_ChangePendientesValue")]
    partial class ChangePendientesValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContadorHandy.Modelos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntregadosAntel")
                        .HasColumnType("int");

                    b.Property<int>("EntregadosClaro")
                        .HasColumnType("int");

                    b.Property<int>("EntregadosETH")
                        .HasColumnType("int");

                    b.Property<int>("EntregadosMovistar")
                        .HasColumnType("int");

                    b.Property<int>("EquiposAntel")
                        .HasColumnType("int");

                    b.Property<int>("EquiposClaro")
                        .HasColumnType("int");

                    b.Property<int>("EquiposETH")
                        .HasColumnType("int");

                    b.Property<int>("EquiposMovistar")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinalizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
